### ISSUE TITLE
Quizlet Live

### ISSUE THREAD

**Issue by Slawijk** [SnowLord7/quizlet#3]
Quizlet has seemed to patch getting a pull req as they now require you to sign in to the creators account thus breaking your script. Thanks for the script though t's served me well.

**Comment by BreadedApples** [comment]
I use a quizlet account and so i don't get that error

**Comment by BreadedApples** [comment]
You dont need the creators account

**Comment by floppian** [comment]
@SnowLord7 you should have done this earlier, but for Quizlet Live use WebSockets. Its the best way. You can do stuff like change your name and account img mid-game.

**Comment by icanc0** [comment]
yep had this problem today, it was fine before
